sudo: required

language: rust
rust:
  - stable
addons:
  apt:
    packages:
      - python3
env:
  matrix:
    - PIP=pip2
    - PIP=pip3


before_script:
  - |
      if [ "$PIP" = pip3 ]; then
        sudo apt-get update
        sudo apt-get install python3-setuptools
        sudo easy_install3 pip
      fi
script:
  - bash ./run-tests.sh
